### ISSUE TITLE
huggingface_hub.utils._errors.LocalEntryNotFoundError

### ISSUE THREAD

**Issue by TQW0909** [mir-aidj/all-in-one#21]
Hi, I keep having the following issue, can u help me plz! Thank you!!!!!

=> Found 0 tracks already analyzed and 1 tracks to analyze.
=> Found 1 tracks already demixed, 0 to demix.
=> Found 1 spectrograms already extracted, 0 to extract.
Traceback (most recent call last):
  File "/Users/tingqiwang/anaconda3/envs/AI_DJ/lib/python3.11/site-packages/urllib3/connectionpool.py", line 775, in urlopen
    self._prepare_proxy(conn)
  File "/Users/tingqiwang/anaconda3/envs/AI_DJ/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1044, in _prepare_proxy
    conn.connect()
  File "/Users/tingqiwang/anaconda3/envs/AI_DJ/lib/python3.11/site-packages/urllib3/connection.py", line 652, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tingqiwang/anaconda3/envs/AI_DJ/lib/python3.11/site-packages/urllib3/connection.py", line 805, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
               ^^^^^^^^^^^^^^^^
  File "/Users/tingqiwang/anaconda3/envs/AI_DJ/lib/python3.11/site-packages/urllib3/util/ssl_.py", line 465, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tingqiwang/anaconda3/envs/AI_DJ/lib/python3.11/site-packages/urllib3/util/ssl_.py", line 509, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tingqiwang/anaconda3/envs/AI_DJ/lib/python3.11/ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tingqiwang/anaconda3/envs/AI_DJ/lib/python3.11/ssl.py", line 1104, in _create
    self.do_handshake()
  File "/Users/tingqiwang/anaconda3/envs/AI_DJ/lib/python3.11/ssl.py", line 1382, in do_handshake
    self._sslobj.do_handshake()
TimeoutError: _ssl.c:989: The handshake operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/tingqiwang/anaconda3/envs/AI_DJ/lib/python3.11/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/Users/tingqiwang/anaconda3/envs/AI_DJ/lib/python3.11/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/Users/tingqiwang/anaconda3/envs/AI_DJ/lib/python3.11/site-packages/urllib3/util/retry.py", line 474, in increment
    raise reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tingqiwang/anaconda3/envs/AI_DJ/lib/python3.11/site-packages/urllib3/util/util.py", line 39, in reraise
    raise value
  File "/Users/tingqiwang/anaconda3/envs/AI_DJ/lib/python3.11/site-packages/urllib3/connectionpool.py", line 777, in urlopen
    self._raise_timeout(
  File "/Users/tingqiwang/anaconda3/envs/AI_DJ/lib/python3.11/site-packages/urllib3/connectionpool.py", line 369, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tingqiwang/anaconda3/envs/AI_DJ/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 1722, in _get_metadata_or_catch_error
    metadata = get_hf_file_metadata(url=url, proxies=proxies, timeout=etag_timeout, headers=headers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tingqiwang/anaconda3/envs/AI_DJ/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/tingqiwang/anaconda3/envs/AI_DJ/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 1645, in get_hf_file_metadata
    r = _request_wrapper(
        ^^^^^^^^^^^^^^^^^
  File "/Users/tingqiwang/anaconda3/envs/AI_DJ/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 372, in _request_wrapper
    response = _request_wrapper(
               ^^^^^^^^^^^^^^^^^
  File "/Users/tingqiwang/anaconda3/envs/AI_DJ/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 395, in _request_wrapper
    response = get_session().request(method=method, url=url, **params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tingqiwang/anaconda3/envs/AI_DJ/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tingqiwang/anaconda3/envs/AI_DJ/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tingqiwang/anaconda3/envs/AI_DJ/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 66, in send
    return super().send(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tingqiwang/anaconda3/envs/AI_DJ/lib/python3.11/site-packages/requests/adapters.py", line 713, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: (ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: a23d297c-fee0-4956-ae58-15e0ed71a05e)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/tingqiwang/anaconda3/envs/AI_DJ/bin/allin1", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/tingqiwang/anaconda3/envs/AI_DJ/lib/python3.11/site-packages/allin1/cli.py", line 53, in main
    analyze(
  File "/Users/tingqiwang/anaconda3/envs/AI_DJ/lib/python3.11/site-packages/allin1/analyze.py", line 124, in analyze
    model = load_pretrained_model(
            ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tingqiwang/anaconda3/envs/AI_DJ/lib/python3.11/site-packages/allin1/models/loaders.py", line 41, in load_pretrained_model
    return load_ensemble_model(model_name, cache_dir, device)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tingqiwang/anaconda3/envs/AI_DJ/lib/python3.11/site-packages/allin1/models/loaders.py", line 72, in load_ensemble_model
    model = load_pretrained_model(model_name, cache_dir, device)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tingqiwang/anaconda3/envs/AI_DJ/lib/python3.11/site-packages/allin1/models/loaders.py", line 53, in load_pretrained_model
    checkpoint_path = hf_hub_download(repo_id='taejunkim/allinone', filename=filename, cache_dir=cache_dir)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tingqiwang/anaconda3/envs/AI_DJ/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/tingqiwang/anaconda3/envs/AI_DJ/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 1221, in hf_hub_download
    return _hf_hub_download_to_cache_dir(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tingqiwang/anaconda3/envs/AI_DJ/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 1325, in _hf_hub_download_to_cache_dir
    _raise_on_head_call_error(head_call_error, force_download, local_files_only)
  File "/Users/tingqiwang/anaconda3/envs/AI_DJ/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 1826, in _raise_on_head_call_error
    raise LocalEntryNotFoundError(
huggingface_hub.utils._errors.LocalEntryNotFoundError: An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.

**Comment by tae-jun** [comment]
Hi, sorry but I can't guess any reason from this error message 😥

What I can see is just there was a problem while downloading the model weights from Hugging Face...

**Comment by TQW0909** [comment]
Thx for the reply! It seems that the program could not download the model from huggingface... Could you let me know wat is the model that is trying to be downloaded so i could potentially try manually downloading the model? Thanks again!!
